# Generated by Django 3.1.5 on 2021-01-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210126_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='spacial_user',
            new_name='special_user',
        ),
    ]
