# Generated by Django 3.1.5 on 2021-01-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images', verbose_name='تصویر'),
        ),
    ]
